// <auto-generated />
using System;
using EmployeeMonitoring.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeMonitoring.Migrations
{
    [DbContext(typeof(EmpContext))]
    partial class EmpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EmployeeMonitoring.Model.EmpModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("EmpregisterModelId")
                        .HasColumnType("int");

                    b.Property<double?>("GacceniliSaatebi")
                        .HasColumnType("float");

                    b.Property<string>("Saxeli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ShesvlisDro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WasvlisDro")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmpregisterModelId");

                    b.ToTable("EmpMonitor", "dbo");
                });

            modelBuilder.Entity("EmployeeMonitoring.Model.EmpregisterModel", b =>
                {
                    b.Property<int>("EmpregisterModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("EmpregisterModelId");

                    b.ToTable("Empregister", "dbo");
                });

            modelBuilder.Entity("EmployeeMonitoring.Model.EmpModel", b =>
                {
                    b.HasOne("EmployeeMonitoring.Model.EmpregisterModel", "EmpregisterModel")
                        .WithMany("EmpModels")
                        .HasForeignKey("EmpregisterModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpregisterModel");
                });

            modelBuilder.Entity("EmployeeMonitoring.Model.EmpregisterModel", b =>
                {
                    b.Navigation("EmpModels");
                });
#pragma warning restore 612, 618
        }
    }
}
